[browser]
# 不用填
ua = ""

[account]
# 你的手机号对应你的密码，必须填，别忘记去掉”#“
 177777777 = "密码"#示范格式：177777777 = "123456" 前面手机号，后面密码

[cookies]

[message_push.Server_chan]
# server酱推送
send_key = ""

[message_push.Wechat_message]
# 微信企业消息
corpid = ""
corpsecret = ""
agentid = ""

[message_push.Dingtalk_message]
# 钉钉推送
access_token = ""

[message_push.Email_message]
# smtp邮件推送
# 发送者邮箱
sender_email = "xxx@163.com"
# 发送者邮箱授权码
sender_password = "xxxaaabbb"
# 邮件接收者邮箱
receiver_email = "bbb@163.com"
# 邮件发送smtp服务器
smtp_server = "smtp.163.com"
# smpt 端口, 务必使用ssl端口
smtp_port = "465"
